# Generated by Django 4.1.2 on 2022-10-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='law_type',
            field=models.CharField(choices=[('CO', 'Constitutional'), ('TR', 'Tax'), ('CI', 'Civil'), ('AD', 'Administrative'), ('CR', 'Criminal'), ('CP', 'Corporate'), ('FA', 'Family'), ('LA', 'LAbor'), ('OT', '(Other)')], default='OT', max_length=2),
        ),
    ]
