# Generated by Django 4.1.2 on 2022-10-14 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0003_lawsuit_date_added_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
