# Generated by Django 4.1.2 on 2022-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0005_alter_movement_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
