# Generated by Django 4.1.2 on 2022-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0006_lawsuit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
